### PR TITLE
Use the new, official, Bolt icon

### PR DESCRIPTION
**Pull request by nmaludy**
Added new icon

### CODE REVIEW

**Comment by Kami** [comment]
LGTM :+1: 

IIRC, we used to have some icon size limit (150px x 150px), but I think this size should probably work as well, since we resize it (at least for Exchange Index).

Would be good to verify what happens when loading the icon in st2web / st2flow. I assume it requests the original size, so if that's the case, it would be good to resize it and make it smaller.

**Comment by Kami** [comment]
I confirmed - most other pack icons are 64x64 px. I will go ahead, resize it and merge it.

Thanks!

**Comment by LindsayHill** [comment]
64x64px was what I always used, but I never checked how it gets handled in st2web. I know Exchange index resizes it these days, but it does make me wonder if we could now allow higher resolution in st2web/st2flow

**Comment by nmaludy** [comment]
I'll do whatever you like, 64x64 is easy enough give me 2 minutes

**Comment by Kami** [comment]
@LindsayHill Yeah, we should see if we can do that, but until then it would be safer to resize it to avoid potential longer load time :)

**Comment by Kami** [comment]
Thanks!

**Pull request merged**
